// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ping

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ping struct {
	_tab flatbuffers.Table
}

func GetRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ping{}
	x.Init(buf, n+offset)
	return x
}

func FinishPingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Ping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Ping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ping) Time() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ping) MutateTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Ping) Server() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Ping) ServerAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Ping) Platform() Platform {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Platform(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Ping) MutatePlatform(n Platform) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *Ping) AsNumber() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Ping) MutateAsNumber(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *Ping) AsName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Ping) PlayerCount() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Ping) MutatePlayerCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func PingStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func PingAddTime(builder *flatbuffers.Builder, time uint64) {
	builder.PrependUint64Slot(0, time, 0)
}
func PingAddServer(builder *flatbuffers.Builder, server flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(server), 0)
}
func PingAddServerAddress(builder *flatbuffers.Builder, serverAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(serverAddress), 0)
}
func PingAddPlatform(builder *flatbuffers.Builder, platform Platform) {
	builder.PrependInt8Slot(3, int8(platform), 0)
}
func PingAddAsNumber(builder *flatbuffers.Builder, asNumber uint32) {
	builder.PrependUint32(asNumber)
	builder.Slot(4)
}
func PingAddAsName(builder *flatbuffers.Builder, asName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(asName), 0)
}
func PingAddPlayerCount(builder *flatbuffers.Builder, playerCount uint32) {
	builder.PrependUint32(playerCount)
	builder.Slot(6)
}
func PingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
