// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ping

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PingBatch struct {
	_tab flatbuffers.Table
}

func GetRootAsPingBatch(buf []byte, offset flatbuffers.UOffsetT) *PingBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PingBatch{}
	x.Init(buf, n+offset)
	return x
}

func FinishPingBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPingBatch(buf []byte, offset flatbuffers.UOffsetT) *PingBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PingBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPingBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PingBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PingBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PingBatch) Source() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PingBatch) Pings(obj *Ping, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PingBatch) PingsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PingBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PingBatchAddSource(builder *flatbuffers.Builder, source flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(source), 0)
}
func PingBatchAddPings(builder *flatbuffers.Builder, pings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(pings), 0)
}
func PingBatchStartPingsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PingBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
