// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ping

import "strconv"

type Platform int8

const (
	Platformunknown Platform = 0
	Platformjava    Platform = 1
	Platformbedrock Platform = 2
)

var EnumNamesPlatform = map[Platform]string{
	Platformunknown: "unknown",
	Platformjava:    "java",
	Platformbedrock: "bedrock",
}

var EnumValuesPlatform = map[string]Platform{
	"unknown": Platformunknown,
	"java":    Platformjava,
	"bedrock": Platformbedrock,
}

func (v Platform) String() string {
	if s, ok := EnumNamesPlatform[v]; ok {
		return s
	}
	return "Platform(" + strconv.FormatInt(int64(v), 10) + ")"
}
